### ISSUE TITLE
Should alarming for open file descriptors be disabled?

### ISSUE THREAD

**Issue by widhalmt** [NETWAYS/check_logstash#11]
In a feedback issue @jordansissel stated that alarming on open file descriptors is something that might not be wanted by every user. Since it is already implemented I changed it a bit but left it in the code.

Now my question is wether alarming / thresholds for open file descriptors should be optional e.g. turned off by command line option.

I'll keep it as performance data because this allows for other checks like check_graphite which should be able to detect spike and anormal rises in open file descriptors which might be a thing one wants to be alerted anyway.

Thresholds by now are percents but performance data are actual counts of open file descriptors.

**Comment by jordansissel** [comment]
+1 on keeping it as count of open files as performance data.

**Comment by dgoetz** [comment]
How about alarm only on 100% by default which will likely cause problems and if someone wants other thresholds he can provide them as parameter?

**Comment by widhalmt** [comment]
Sounds reasonable, @dgoetz . Thanks

**Comment by martialblog** [comment]
I'm planning a rewrite of this Plugin that will address this issue. Release is scheduled for January 2023.
