### ISSUE TITLE
events.out should be shown as average instead of total counts

### ISSUE THREAD

**Issue by MarcusCaepio** [NETWAYS/check_logstash#31]
Hi Thomas,
I noticed that the perfdata for the .events.out are counted. 
I currently have a very huge events.out count (1,399,787,534.00 :D )
Wouldn't it be better to calculate the average like it's done with the inflight events?

Cheers,
Marcus

**Comment by widhalmt** [comment]
Hi,

I wanted a continous counter (like in https://www.monitoring-plugins.org/doc/guidelines.html#AEN201 ) . As far as my experience goes, this is better with graphers like Graphite or PNP4Nagios. Some tools can calculate averages and rate from counters but not the other way around.

Is that ok for you? Calculating and average in this case meant to store them in a temporary file or change the call of the check to give the last result. Which are both things that make the plugin less easy to handle.

The inflight events give the current rate, not an average. The calculation is done within Logstash not in the plugin.

Is that ok for you or do you need the average? The only way I can think of implementing it is in addition to the counter so your problem might not be solved.

**Comment by MarcusCaepio** [comment]
tbh, I don't see a benefit of a growing counter. The interesting part for me is the delta between the checks to see, if there are peaks between them without the need of doing magic in grafana. Also I don't know, if a neverending growing value has downsides in my InfluxDB.

**Comment by martialblog** [comment]
I agree with @widhalmt this adds quite some logic to the Plugin. Personally I think this would be more fitting for a either a metrics exporter or the Time series database should support calculating this.
