### ISSUE TITLE
Make use of the new formatting options in Icinga Web 2 

### ISSUE THREAD

**Issue by widhalmt** [NETWAYS/check_logstash#32]
When you write the status like `[OK]` or `[WARNING]` in Icinga Web 2 2.7+ it gets highlighted automatically. No matter if this is part or a multiline output or not.

We should use that.

**Comment by ysibirski** [comment]
Apologies @widhalmt  in advance If it is the wrong place to ask the following question, but is `x-pack` installation required in order for `check_logstash` to work? The reason I am asking is my logstash service is running in AWS ECS as stand-alone task that I am trying to find the way to monitor somehow.

Thank you in advance.

**Comment by widhalmt** [comment]
@ysibirski Yes, you're right, that's totally the wrong place to ask that. :-) But nevermind, that won't keep me from trying to help you.

The Logstash-API is free to use as it's said in the [Logstash documentation](https://www.elastic.co/guide/en/logstash/current/monitoring-logstash.html). So you can use it without any Subscription. You can set `http.host` and `http.port` if you have access to `logstash.yml`. Most installations I saw have it activated by default and running an port `9600/tcp`. Might be that it's only accessible from `localhost` but that's to be checked in your configuration or in the services' options.

**Comment by ysibirski** [comment]
> @ysibirski Yes, you're right, that's totally the wrong place to ask that. :-) But nevermind, that won't keep me from trying to help you.
> 
> The Logstash-API is free to use as it's said in the [Logstash documentation](https://www.elastic.co/guide/en/logstash/current/monitoring-logstash.html). So you can use it without any Subscription. You can set `http.host` and `http.port` if you have access to `logstash.yml`. Most installations I saw have it activated by default and running an port `9600/tcp`. Might be that it's only accessible from `localhost` but that's to be checked in your configuration or in the services' options.

Thank you very much @widhalmt  for the clarification. I can take if from here now on.

**Comment by martialblog** [comment]
I'm planning a rewrite of this Plugin that will address this issue. Release is scheduled for January 2023.
