### ISSUE TITLE
--inflight-events-warn and --inflight-events-crit not working correctly. (false positive alarms)

### ISSUE THREAD

**Issue by iovcho** [NETWAYS/check_logstash#42]
Hello. I have issue using this plugin using custom alarms for inflight-events-warn and inflight-events-crit
Here is the output without parameters:
[root@coreinit check_logstash]# ./check_logstash -H localhost
OK - Logstash seems to be doing fine. | process.cpu.percent=1%;;;0;100 jvm.mem.heap_used_percent=65%;70;80;0;100 jvm.threads.count=58;;;0; process.open_file_descriptors=186;13855;15485;0;16384 pipelines.main.events.out=76185331c;;;0; inflight_events_main=-76786;;;0;
OK: CPU usage in percent: 1
OK: Config reload syntax check: main: OK;
OK: Inflight events: main: -76786;
OK: Heap usage at 65.00% (1374317728 out of 2112618496 bytes in use)
OK: Open file descriptors at 1.14%. (186 out of 16384 file descriptors are open)

Here is the test with parameters --inflight-events-warn 100000 --inflight-events-crit 200000:
[root@coreinit check_logstash]# ./check_logstash -H localhost --inflight-events-warn 100000 --inflight-events-crit 200000
CRITICAL - Logstash is unhealthy - CRITICAL: Inflight events: main: -76624; | process.cpu.percent=1%;;;0;100 jvm.mem.heap_used_percent=53%;70;80;0;100 jvm.threads.count=58;;;0; process.open_file_descriptors=187;13855;15485;0;16384 pipelines.main.events.out=76189183c;;;0; inflight_events_main=-76624;100000;200000;0;
CRITICAL: Inflight events: main: -76624;
OK: CPU usage in percent: 1
OK: Config reload syntax check: main: OK;
OK: Heap usage at 53.00% (1134559128 out of 2112618496 bytes in use)
OK: Open file descriptors at 1.14%. (187 out of 16384 file descriptors are open)

Logstash Version: logstash-7.6.2-1.noarch
Can you help me with this issue ?
Best regards,

**Comment by martialblog** [comment]
I'm planning a rewrite of this Plugin that will address this issue. Release is scheduled for January 2023.
