### ISSUE TITLE
Inflight events check cannot work with 7.17.0+

### ISSUE THREAD

**Issue by eLvErDe** [NETWAYS/check_logstash#44]
Hello,

Logstash stats API has changed and out counter does not include anymore items discarded by a filter option so there is no more any way to known if in - out difference is lagging or discarded items.

I opened a ticket trying to explain why I think it's a bad idea, let's see if they answer:
https://github.com/elastic/logstash/issues/14069

Regards,

**Comment by martialblog** [comment]
I'm planning a rewrite of this Plugin that will address this issue. Release is scheduled for January 2023.

**Comment by martialblog** [comment]
Since it's an issue with Logstash itself, it won't be addressed in the new Release. I'll keep an eye on the issue though :eye:

**Comment by martialblog** [comment]
While working with a newer Logstash Version I noticed that there now are "Flow Metrics" in the API, which represent the same as the "Inflight Events" we have defined in the Plugin.

https://www.elastic.co/guide/en/logstash/8.7/logstash-8-5-0.html

I think these metrics could be a replacement when working with Logstash 7.17.0+

I'm already working on adding them to the Plugin

**Comment by martialblog** [comment]
I will close this with regards to https://github.com/NETWAYS/check_logstash/pull/72

Since the Logstash API now provides health metrics natively, using these provides a better solution than the Events we calculated.
