### ISSUE TITLE
[Feature Request] Select pipeline for inflight events 

### ISSUE THREAD

**Issue by MarcusCaepio** [NETWAYS/check_logstash#45]
Hi @widhalmt 
We have a logstash with several pipelines defined, where on the one side, some pipelines always have to get inflight events and on the other side, some only get events on demand. We would like to monitor the inlight events of the important pipelines only and set ranges for them. Currently a range of "1:" triggers alerts, because the "on demand" pipelines are not getting events (or different amounts, so we could use different trigger values)

Cheers,
Marcus

**Comment by martialblog** [comment]
I'm planning a rewrite of this Plugin that will address this issue. Release is scheduled for January 2023.

**Comment by MarcusCaepio** [comment]
> I'm planning a rewrite of this Plugin that will address this issue. Release is scheduled for January 2023.

We already did this ourselves and opened a PR on July 18th, which has not received any attention so far

**Comment by martialblog** [comment]
Thanks I will have a look at it.
