### ISSUE TITLE
events.in and events.out missing counter character in performance data

### ISSUE THREAD

**Issue by MSConsults** [NETWAYS/check_logstash#52]
In the new go based version - values for events.in and events.out should end with a "c" for counter types:

pipelines.mycrazypipe.events.in=123**c**
pipelines.mycrazypipe.events.out=456**c**

According to https://www.monitoring-plugins.org/doc/guidelines.html#AEN201

Then nagios/icinga/... knows how to process this values properly.

**Comment by martialblog** [comment]
Hi, thanks for using the new version and for the feedback. 

I will fix that :+1:

**Comment by martialblog** [comment]
@MSConsults I added the missing units. Thanks again!

Let me know if there's anything else with the new version. Feedback is very welcome.
