### ISSUE TITLE
UNKNOWN - Could not determine status (*errors.errorString)

### ISSUE THREAD

**Issue by Tontonitch** [NETWAYS/check_logstash#63]
logstash: 6.8.23
check_logstash: 0.8.0

```
# ./check_logstash_0.8.0_Linux_x86_64 health
UNKNOWN - Could not determine status (*errors.errorString)
#
```

**Comment by martialblog** [comment]
Hi, I added some basic backwards compatibility in the Plugin. It should now also work with Logstash 6 after the PR is merged.
