### ISSUE TITLE
 Undefined metric: invalid metric value 'green'

### ISSUE THREAD

**Issue by solarisfire** [NETWAYS/check_logstash#84]
Is it possible to remove status=green from the performance metric output to keep this backwards compatible with Nagios?

Doing this with: 

check_logstash health | sed 's/status=[a-zA-Z]\+//g'

isn't super elegant...

**Comment by martialblog** [comment]
Hi, yeah that's something we should change.

**Comment by RincewindsHat** [comment]
Fixed by #85

**Comment by martialblog** [comment]
Is in the new release https://github.com/NETWAYS/check_logstash/releases/tag/v0.9.1

**Comment by solarisfire** [comment]
Wow, thanks for the rapid turnaround guys! 👍
