### ISSUE TITLE
[Feature]: connection refused (*url.Error) as CRITICAL or UNKNOWN

### ISSUE THREAD

**Issue by MarcusCaepio** [NETWAYS/check_logstash#98]
### Describe the feature request

Good Morning,
An connection refused error is an indication for a failed logstash instance. Currently the plugin marks this as Unknown. It would be nice to set this as critical.

Cheers,
Marcus

**Comment by martialblog** [comment]
Hi, 

which sub-command are you referring to? 

The `health` command is currently defined as "if the Logstash instance is not the given warning/critical thresholds it's healthy. If we can't determine the thresholds it's unknown."

But one could argue that if we can't reach it, it's critical. One could also argue that if we can't reach it we cannot know if it's up or down. 

Let me think about it :thinking: 

@RincewindsHat do you have an opinion?

**Comment by martialblog** [comment]
Jup that's an idea :+1:

**Comment by martialblog** [comment]
I added a `--unreachable-state` flag here #99 

This flag can be used to pass an integer which will be the exit code.

**Comment by martialblog** [comment]
The feature will be in the next release.

Thanks for the suggestion!
